; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-n16r8]
platform = espressif32@7.0.0
framework = arduino
board = esp32-s3-devkitc-1-n16r8
monitor_speed = 115200
build_flags = 
	-I include
	# -Wno-deprecated-declarations
	# -Wno-cpp
	# -Wno-return-type
	# Debug flags
	-DCORE_DEBUG_LEVEL=0        # Desativa logs de debug do ESP
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_SPIRAM_CACHE_WORKAROUND=1
	# Configurações do Nextion
	-DNEXTION_SERIAL=Serial2
	-DNEXTION_BAUD=9600        # Define baud rate do Nextion
board_build.filesystem = littlefs
lib_deps =
	adafruit/MAX6675 library@^1.1.2
	itead/Nextion@^0.9.0
	ottowinter/ESPAsyncWebServer-esphome@^3.4.1
	knolleary/PubSubClient@^2.8
	SPI
	plerup/EspSoftwareSerial@^8.2.0
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
	bblanchon/ArduinoJson@^7.4.3
	tzapu/WiFiManager@^2.0.17
upload_protocol = esptool
debug_tool = esp-builtin
